name: CI

on:
    push:
        branches:
            - master
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - uses: actions/setup-node@v2
              with:
                  cache: 'pnpm'

            - run: pnpm install

            - run: pnpm run -r build --if-present

    eslint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - uses: actions/setup-node@v2
              with:
                  cache: 'pnpm'

            - run: pnpm install

            - run: pnpm exec eslint ./packages

    typings:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - uses: actions/setup-node@v2
              with:
                  cache: 'pnpm'

            - run: pnpm install

            - run: tsc --noEmit

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - uses: actions/setup-node@v2
              with:
                  cache: 'pnpm'

            - run: pnpm install

            - run: pnpm -r run test:coverage --if-present

            - uses: codecov/codecov-action@v2
              with:
                  fail_ci_if_error: true
                  verbose: true
