name: CI

on:
    push:
        branches:
            - master
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Build bundle
              run: pnpm run -r build --if-present

    eslint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: eslint
              run: pnpm exec eslint ./packages

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Test with coverage
              run: pnpm -r run test:coverage --if-present

            - name: Code coverage
              uses: codecov/codecov-action@v2
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
                  fail_ci_if_error: true
                  verbose: true
